// D:\\PRJ_YCT_Final\\routes\\mlmRoutes.js

const express = require('express');
const router = express.Router();
const { 
    addDownline, 
    getDownline, 
    getDownlineHierarchy, 
    getTeamPerformance, 
    generateTeamReport, 
    getReports, 
    getReportDetail 
} = require('../controllers/mlmController');
const { protect, authorizeCoach } = require('../middleware/auth');
const { updateLastActive } = require('../middleware/activityMiddleware');

// ===== DOWNLINE MANAGEMENT =====

// Route 1: Add a new coach to a sponsor's downline (Private)
// This route requires authentication and will update the lastActiveAt timestamp
router.post('/downline', protect, updateLastActive, authorizeCoach('coach'), addDownline);

// Route 2: Get the direct downline for a specific sponsor (Private)
// Enhanced with performance data option
router.get('/downline/:sponsorId', protect, updateLastActive, authorizeCoach('coach'), getDownline);

// Route 3: Get the entire nested downline hierarchy for a specific coach (Private)
// Enhanced with performance data and configurable levels
router.get('/hierarchy/:coachId', protect, updateLastActive, authorizeCoach('coach'), getDownlineHierarchy);

// ===== TEAM PERFORMANCE TRACKING =====

// Route 4: Get comprehensive team performance summary (Private)
// Provides detailed performance metrics for all downline coaches
router.get('/team-performance/:sponsorId', protect, updateLastActive, authorizeCoach('coach'), getTeamPerformance);

// ===== REPORT GENERATION & MANAGEMENT =====

// Route 5: Generate comprehensive team report (Private)
// Creates detailed reports with AI insights and analytics
router.post('/generate-report', protect, updateLastActive, authorizeCoach('coach'), generateTeamReport);

// Route 6: Get list of generated reports (Private)
// Retrieves all reports generated by a coach
router.get('/reports/:sponsorId', protect, updateLastActive, authorizeCoach('coach'), getReports);

// Route 7: Get specific report details (Private)
// Retrieves complete report data including insights and analytics
router.get('/reports/detail/:reportId', protect, updateLastActive, authorizeCoach('coach'), getReportDetail);

module.exports = router;