// D:\\PRJ_YCT_Final\\routes\\mlmRoutes.js

const express = require('express');
const router = express.Router();
const { 
    addDownline, 
    getDownline, 
    getDownlineHierarchy, 
    getTeamPerformance, 
    generateTeamReport, 
    getReports, 
    getReportDetail 
} = require('../controllers/mlmController');

const { 
    unifiedCoachAuth, 
    requirePermission, 
    checkResourceOwnership,
    filterResourcesByPermission 
} = require('../middleware/unifiedCoachAuth');
const { updateLastActive } = require('../middleware/activityMiddleware');

// ===== DOWNLINE MANAGEMENT =====

// Route 1: Add a new coach to a sponsor's downline (Private)
// This route requires authentication and will update the lastActiveAt timestamp
// Only coaches can add to their own downline
router.post('/downline', unifiedCoachAuth(), updateLastActive, requirePermission('mlm:manage'), addDownline);

// Route 2: Get the direct downline for a specific sponsor (Private)
// Enhanced with performance data option
// Staff can view their coach's downline if they have permission
router.get('/downline/:sponsorId', unifiedCoachAuth(), updateLastActive, requirePermission('mlm:read'), getDownline);

// Route 3: Get the entire nested downline hierarchy for a specific coach (Private)
// Enhanced with performance data and configurable levels
// Staff can view their coach's hierarchy if they have permission
router.get('/hierarchy/:coachId', unifiedCoachAuth(), updateLastActive, requirePermission('mlm:read'), getDownlineHierarchy);

// ===== TEAM PERFORMANCE TRACKING =====

// Route 4: Get comprehensive team performance summary (Private)
// Provides detailed performance metrics for all downline coaches
// Staff can view their coach's team performance if they have permission
router.get('/team-performance/:sponsorId', unifiedCoachAuth(), updateLastActive, requirePermission('mlm:read'), getTeamPerformance);

// ===== REPORT GENERATION & MANAGEMENT =====

// Route 5: Generate comprehensive team report (Private)
// Creates detailed reports with AI insights and analytics
// Staff can generate reports if they have permission
router.post('/generate-report', unifiedCoachAuth(), updateLastActive, requirePermission('mlm:manage'), generateTeamReport);

// Route 6: Get list of generated reports (Private)
// Retrieves all reports generated by a coach
// Staff can view their coach's reports if they have permission
router.get('/reports/:sponsorId', unifiedCoachAuth(), updateLastActive, requirePermission('mlm:read'), getReports);

// Route 7: Get specific report details (Private)
// Retrieves complete report data including insights and analytics
// Staff can view their coach's reports if they have permission
router.get('/reports/detail/:reportId', unifiedCoachAuth(), updateLastActive, requirePermission('mlm:read'), getReportDetail);

module.exports = router;